name: sparsegpt
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.*
  - pip # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.3.2
  - cudatoolkit
  - pytorch

